# Generated by Django 5.2.4 on 2025-08-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_location',
            field=models.CharField(blank=True, help_text='End city/village if applicable (Outstation/Round Trip)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_location',
            field=models.CharField(blank=True, help_text='Name of ending drop place (if different)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='How many hours (for hourly rental). If not used, leave blank.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='luggage_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_passengers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(default='Unknown location', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='For round trip or outstation. Null for hourly/oneway.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fare_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.ForeignKey(help_text='Type of trip/rental (Hourly, Oneway, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.triptype'),
        ),
    ]
