# Generated by Django 5.2.4 on 2025-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], default='Sedan', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
