# Generated by Django 5.2.4 on 2025-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_car_car_type_car_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='cars', to='car_rental.carfeature'),
        ),
    ]
