# Generated by Django 5.2.4 on 2025-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0009_remove_car_image_urls_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='media/car_image/'),
        ),
    ]
