# Generated by Django 5.2.4 on 2025-08-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
