# Generated by Django 5.2.4 on 2025-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_car_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trip_types',
            field=models.ManyToManyField(blank=True, related_name='cars', to='car_rental.triptype'),
        ),
    ]
