# Generated by Django 5.2.4 on 2025-08-10 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_tempbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempbooking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
